### ISSUE TITLE
Demo case 4

### ISSUE THREAD

**Issue by PenguinNell** [kkang7/CDSeq#1]
Dear Kai Kang,

when I try to complete case 4 in Demo.m I get "Undefined function 'corr' for input arguments of type 'double'." and I can't find this function (it need in CDSeq.m at line 153).

With best wishes,
Anastasiia

**Comment by kkang7** [comment]
Dear Anastasiia,

Quick question. Are you running CDSeq version 014?

Best,
Kai

**Comment by PenguinNell** [comment]
Yes

**Comment by kkang7** [comment]
> Yes

Hi Anastasiia, I tried on my machine and it has no error reported. 

corr is a function in statistics and ML toolbox: https://www.mathworks.com/help/stats/referencelist.html?type=function

so you may need to install this tool box to use the "corr" function. 

the discussion here may also be helpful: 
https://www.mathworks.com/matlabcentral/answers/5200-undefined-function-or-method-for-input-arguments-of-type-double

**Comment by PenguinNell** [comment]
Hi Kai,

Now it works! Thank you a lot! I just never used Matlab before.

With best wishes,
Anastasiia

**Comment by kkang7** [comment]
> Hi Kai,
> 
> Now it works! Thank you a lot! I just never used Matlab before.
> 
> With best wishes,
> Anastasiia

Glad to hear that Anastasiia!
